version: '3'

services:
  app:
    build: .
    ports:
      - 3030:3030
    depends_on:
      - db
    environment:
      - DB=mongodb://db:27017/UserAuthDB

  db:
    image: mongo
    ports:
      - 27017:27017