###

POST  http://localhost:3030/users/sub
content-type: application/json

{
    "fullName": "Rais Othmane",
    "email": "Othmane3@test.com",
    "password" :"1234",
    "role" :["6422f2652aec11858f2e8bfe","6422f26d2aec11858f2e8c00"]
}

###
POST  http://localhost:3030/users/login
content-type: application/json

{
    "email": "Othmane3@test.com",
    "password" :"1234"
}

###
POST  http://localhost:3030/Roles/Add
content-type: application/json

{
    "roleCode": "supervisor",
    "roleDesc" :"supervisor appli"
}


###
GET http://localhost:3030/roles/find
content-type: application/json
 